### ISSUE TITLE
Add A Pop-Up To The Tip-Calculator

### ISSUE THREAD

**Issue by Aman254** [Aman254/TipCalculator-Project#1]
On the Tip-Calculator Whenever a Person Enters Amount On the Amount Box its Fine. 

But Whenever a User Enters String I gives ERROR called NAN. 

Add A **POPUP**  Feature Using JavaScript Whenever the user Enters the String it Gives a Pop-up 
{ Popup Telling;  Hey Looks Like You Not Entering a Number Please Enter The Number To Get the Tip-Amount} 

Here Is the Calculator Preview: [https://tipcalculator-project.aman254.repl.co/]

**Comment by alchuu00** [comment]
Hi @Aman254 , I'd like to solve this issue. Can you assign it to me please 😊

**Comment by Aman254** [comment]
@alchuu00 .  Sure I'll Assign You With help Of You The Project Will Be more Enhanced And Dynamic

**Comment by Aman254** [comment]
@alchuu00  I'll Also Share My Replit  Ropo  so It will be More Convenient for You To Understand and Work On It  
[https://replit.com/@Aman254/TipCalculator-Project](url)

**Comment by alchuu00** [comment]
@Aman254  Do you have any design in mind, like where should the pop-up be? Below the input?

**Comment by Aman254** [comment]
@alchuu00  No Design  in my mind  yet.😔

 You can pop-up it anywhere in the project.  

It will be better if you make the popup on the right top of the calculator.

**Comment by Aman254** [comment]
@alchuu00 You are free to add your own idea and also if you want to update css you can't it totally up to you.

**Comment by alchuu00** [comment]
@Aman254 Okay, I will put it in the top right corner

**Comment by Aman254** [comment]
Sure, Proceed Forward

**Comment by alchuu00** [comment]
@Aman254  I added popup and opened pull request

**Comment by Aman254** [comment]
@alchuu00 Excellent! it Was great and Am Also Building a rock paper scissors game and as am Beginner now in Development 
I will need your help and lets collaborate and make few more awesome projects, that can enhance our portfolio. 

Are You Interested?

**Comment by alchuu00** [comment]
@Aman254 Yes I am interested, it would be nice to make some projects together :)
